---
- import_playbook: playbooks/kube-dependencies.yml
- import_playbook: playbooks/configure_master_node.yml
- import_playbook: playbooks/configure_worker_node.yml
- import_playbook: playbooks/configure_k8_addons.yml
